version: '3.8'

services:
  auth-service:
    build: ./backend/auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    env_file:
      - .env
    depends_on:
      - db-service

  db-service:
    build: ./backend/db-service
    ports:
      - "${DB_SERVICE_PORT}:${DB_SERVICE_PORT}"
    env_file:
      - .env
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - db-service

  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
