version: '3.8'

services:
  auth-service:
    build: ./backend/auth-service
    ports:
      - "8081:8081"
    depends_on:
      - db-service

  db-service:
    build: ./backend/db-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - db-service

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dental_ai
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
