import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "@/context/SessionContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <Toaster position="top-center" />
          <main className="min-h-screen w-full grid place-items-center px-4 bg-gray-50 dark:bg-gray-900">
            {children}
          </main>
        </SessionProvider>
        {/* Used in our sidebar */}
        <script src="https://unpkg.com/flowbite@latest/dist/flowbite.min.js"></script>
      </body>
    </html>
  );
}
